language: python

sudo: false

env:
    global:
        - CONDA_DEPENDENCIES='pyqt traitlets ipython_genutils jupyter_core jupyter_client pygments ipykernel pytest pytest-cov'
        - PIP_DEPENDENCIES='coveralls'

matrix:
    include:
        - python: "3.6"
        - python: "3.5"
        - python: "2.7"
          env: PIP_DEPENDENCIES="coveralls mock"

install:
    - git clone --depth 1 git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

script:
    - pytest -x -vv --cov=qtconsole qtconsole

after_success:
    - coveralls
